### ISSUE TITLE
[ Enhancement ] Add Tower Connect for 24.1

### ISSUE THREAD

**Issue by gwright99** [seqeralabs/cx-field-tools-installer#88]
As per [documentation efforts for Tower 24.1](https://github.com/seqeralabs/docs/pull/78/files/9bebd6a28d0d4576d32b46024b70c3d91dfaeae6..31e975c9d9cecdf9a8394fb6a9b1604b350949ea), Data Studio functionality requires an additional container(s\0 to be added to the Docker Compose project.

Changes required (_based on in-progress Dev docs PR [here](https://github.com/seqeralabs/docs/pull/78/files)_):
- PEM file generation
- Mounting of PEM into `backend` container.
- New container x2
- Modification of `TOWER_DB_URL` in _tower.env_
- Addition of [new entries](platform_versioned_docs/version-24.1.0/enterprise/_templates/docker/tower.env) to _tower.env_
- DNS changes?

Working with @weronikasosnowskaseqera re specific details.

**Comment by gwright99** [comment]
## Tasks:

#### _terraform.tfvars_ changes
- [ ] Add new "Data Studio" section:
    - [ ] _templates/TEMPLATE_terraform.tfvars_ 
    - [ ] _variables.tf_
- [ ] Add flag `flag_enable_datastudio`:
    - [ ] _templates/TEMPLATE_terraform.tfvars_ 
    - [ ] _variables.tf_
...

**Comment by markpanganiban** [comment]
**tower.env.tpl changes**
- [ ] Add the default data studios template on tower.env file.
